#!/bin/bash

jack_wait -w

while true
do
    jack_lsp > /dev/c_lsp
    wait
    diff /dev/p_lsp /dev/c_lsp > /dev/d_lsp

    if grep "<" /dev/d_lsp > /dev/null 2>&1
    then 
        echo "DISCONNECTING" $(date) 
        while read line
        do
            i=$(echo $line | cut -f 1 -d ":" | cut -f 2 -d "_")
            w=$(echo $line | cut -f 2 -d ":" | cut -f 1 -d "_")
            d=$(echo $line | cut -f 2 -d ":" | cut -f 2 -d "_")
            if [[ $w == "send" ]]
            then
                # echo "SEND" $line
                echo "jack_disconnect pdmixer:output$((d-1)) $line"
            else
                # echo "RECEIVE" $line
                i=$((i-1))
                i=$((i*2))
                d=$((d-1))
                echo "jack_disconnect $line pdmixer:input$((i+$d))"
            fi
        done < <(grep "<" /dev/d_lsp | awk '{print $2}')
    elif grep ">" /dev/d_lsp > /dev/null 2>&1
    then
        echo "CONNECTING" $(date) 
        while read line
        do
            i=$(echo $line | cut -f 1 -d ":" | cut -f 2 -d "_")
            w=$(echo $line | cut -f 2 -d ":" | cut -f 1 -d "_")
            d=$(echo $line | cut -f 2 -d ":" | cut -f 2 -d "_")
            if [[ $w == "send" ]]
            then
                # echo "SEND" $line
                echo "jack_connect pdmixer:output$((d-1)) $line"
            else
                # echo "RECEIVE" $line
                i=$((i-1))
                i=$((i*2))
                d=$((d-1))
                echo "jack_connect $line pdmixer:input$((i+$d))"
            fi
        done < <(grep ">" /dev/d_lsp | awk '{print $2}')
    fi
    cat /dev/c_lsp > /dev/p_lsp
    sleep 1
done
